### ISSUE TITLE
Little mistake on the page

### ISSUE THREAD

**Issue by alexandreborges** [OALabs/findyara-ida#1]
Herrcore,

Good morning. How are you?

Please, if you have free time, fix the instructions on the page. The correct command line is **pip install yara-python** (you wrote _pip install python-yara_).

I hope you have an amazing week.

**Alexandre Borges
(twitter: @ale_sp_brazil)**

**Comment by herrcore** [comment]
Oh thanks for spotting that! My mistake 😊 

Fixed:
https://github.com/OALabs/FindYara/commit/ba194bf1341beb001be4ef1411922821e95cb7ed#diff-04c6e90faac2675aa89e2176d2eec7d8
