### ISSUE TITLE
Yara Match Object is Now a Dictionnary

### ISSUE THREAD

**Issue by cyril-t-f** [OALabs/findyara-ida#10]
Hello!

FindYara doesn't work anymore, it seems Yara devs changed their Match class for a dictionnary:

![image](https://user-images.githubusercontent.com/99127082/197995480-cc30921c-6309-4c0a-98ef-b84954908347.png)

![image](https://user-images.githubusercontent.com/99127082/197995341-f4b8ec69-a532-46f9-a7d8-ab28a8da30ad.png)

**Comment by cyril-t-f** [comment]
Nvm I wasn't using the right yara module!

**Comment by shlomig123** [comment]
Having the same error while yara module is uninstalled and yara-python version is 4.3.1 
any solutions?
